---
controller_credentials_sand:
  - name: "credential-windows-test"
    description: ""
    credential_type: "Machine"
    organization: "org-windows"
    inputs:
      become_method: ''
      become_username: ''
      password: 'none'
      username: admin
...
